FROM ubuntu:22.04 AS builder

RUN apt-get update && apt-get install -y curl gnupg git

# Instalar Node.js 20 + Angular CLI
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
  && apt-get install -y nodejs \
  && npm install -g @angular/cli \
  && apt-get clean

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Construir el frontend
RUN npm run build

# Imagen final con nginx
FROM nginx:alpine
COPY --from=builder /app/dist/frontend/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
